services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-stack-db
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      
  redis:
    image: redis
    restart: always
    container_name: nextcloud-stack-redis
    volumes:
      - cache:/usr/local/etc/redis
      - cache:/data

  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    container_name: nextcloud-stack-office
    ports:
      - 8082:80
      - 8083:443
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - onlyoffice:/var/log/onlyoffice
      - onlyoffice:/var/www/onlyoffice/Data
      - onlyoffice:/var/lib/rabbitmq
      - onlyoffice:/var/lib/redis
      - onlyoffice:/usr/share/fonts/truetype/custom
      - onlyoffice:/var/lib/onlyoffice
      - onlyoffice:/var/lib/postgresql
  nextcloud:
    image: nextcloud:latest
    restart: always
    container_name: nextcloud-stack-app
    ports:
      - 8080:80
      - 8081:443
    depends_on:
      - db
      - redis
      - onlyoffice
    volumes:
      - data:/var/www/html
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextcloud-stack-db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
      - REDIS_HOST=nextcloud-stack-redis
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://${DOMAIN}/
      - OVERWRITEWEBROOT=/
volumes:
  db:
  cache:
  onlyoffice:
  data:

    


