services:
 # Nextcloud Caddy
  nextcloud-caddy:
    build:
      context: ./caddy
      args:
        - TAG_NAME=hpb_proxy
    image: hpb_proxy
    container_name: nextcloud-stack-cady
    depends_on:
      nextcloud-talk:
        condition: service_started
        required: false
      nextcloud-recording:
        condition: service_started
        required: false
    init: true
    ports:
      - 443:443/tcp
      - 443:443/udp
    environment:
      - HPB_DOMAIN=${HPB_DOMAIN}
    restart: unless-stopped
    networks:
      - hpb_network
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile

  # Nextcloud talk
  nextcloud-talk:
    build:
      context: ./talk
      args:
        - TAG_NAME=hpb_talk
    image: hpb_talk
    container_name: nextcloud-stack-talk
    init: true
    ports:
      - 3478:3478/tcp
      - 3478:3478/udp
      # - 8081:8081 # Uncomment if you use a different Revers Proxy installed on the host directly like NGINX.
    expose:
      - "8081"
    environment:
      - NC_DOMAIN=${NC_DOMAIN}
      - TURN_SECRET=${TURN_SECRET}
      - SIGNALING_SECRET=${SIGNALING_SECRET}
      - TZ=${TZ}
      - TALK_PORT=${TALK_PORT}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - HPB_DOMAIN=${HPB_DOMAIN}
    restart: unless-stopped
    networks:
      - hpb_network
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /opt/eturnal/run
      - /conf
      - /tmp

  # Nextcloud recording
  nextcloud-recording:
    build:
      context: ./recording
      args:
        - TAG_NAME=hpb_recording
    image: hpb_recording
    container_name: nextcloud-stack-recording
    init: true
    expose:
      - "1234"
    #ports:
    # - 1234:1234 # Uncomment if you use a different Revers Proxy installed on the host directly like NGINX.
    environment:
      - NC_DOMAIN=${NC_DOMAIN}
      - TZ=${TZ}
      - RECORDING_SECRET=${RECORDING_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - HPB_DOMAIN=${HPB_DOMAIN}
    shm_size: 2147483648
    restart: unless-stopped
    networks:
      - hpb_network
    tmpfs:
      - /tmp
      - /conf

networks:
  hpb_network:
    name: hpb_network
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd12:3456:789a:2::/64
